config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'api/eadaptor' => 'api#eadaptor'
  post 'api/eadaptor' => 'api#eadaptor'
  put 'api/eadaptor' => 'api#eadaptor'

  resources :organizations, except: [:show]
  resources :client_accounts
  resources :email
  resources :shipments
  resources :invoices do
    collection do
      get :export
    end
  end

  get 'email_sync' => 'email#sync'

  get 'organizations/import' => 'organizations#import'
  get 'organizations/import_contacts' => 'organizations#import_contacts'
  post 'organizations/upload' => 'organizations#upload'
  post 'organizations/upload_contacts' => 'organizations#upload_contacts'

  post "google/auth", to: "google#auth"
  get "google/auth", to: "google#auth"

  post "oauth2callback", to: "google#auth"
  get "oauth2callback", to: "google#auth"

  post 'cargowise_shipment' => 'cargowise#create_shipment'

  root to: 'static#index'
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :client_account
  has_many :organization_contacts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :client_account
  has_many :emails
  has_many :documents
  has_many :organizations

  def all_documents
    Document.where(user_id: id).or(Document.where(client_account_id: client_account_id))
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # require user
  before_action :authenticate_user!

  def import
  end

  def import_contacts
  end

  def index
    @organization_ids = Organization.where(client_account_id: current_user.client_account_id).ids
    @organization_contacts_size = OrganizationContact.where(organization_id: @organization_ids).size
  end

  def upload
    xlsx = Roo::Spreadsheet.open(params[:file].path)
    sheet_h = xlsx.parse(headers: true)
    sheet_h[1..-1].each do |row|
      org = Organization.find_or_create_by(
        user_id: current_user.id,
        organization_code: row["Organization Code"],
        unloco: row["UNLOCO"]
      )

      org.assign_attributes(
        user_id: current_user.id,
        client_account_id: current_user.client_account_id,
        organization_code: row["Organization Code"],
        full_name: row["Full Name"],
        unloco: row["UNLOCO"],
        city: row["City"],
        state: row["State"],
        branch: row["Branch"],
        screening_status: row["Scrn."],
        achievable_business: row["Achievable Business"],
        category: row["Category"],
        country_region: row["Country/Region"],
        employer_identification_number: row["Employer Identification Number"],
        imp_bond_last_queried_date: row["Imp. Bond Last Queried Date"],
        created_by: row["Created By"],
        created_time_utc: row["Created Time (UTC)"],
        last_edit: row["Last Edit"],
        last_edited_time_utc: row["Last Edited Time (UTC)"],
        address_1: row["Address 1"],
        address_2: row["Address 2"],
        email: row["Email"]
      )

      org.save if org.valid? && org.changed?
    end

    redirect_to organizations_path
  end

  def upload_contacts
    xlsx = Roo::Spreadsheet.open(params[:file].path)
    sheet_h = xlsx.parse(headers: true)
    sheet_h[1..-1].each do |row|
      contact = OrganizationContact.find_or_create_by(
        contact_name: row["Contact Name"],
        organization_code: row["Organization"],
        organization_name: row["Organization Name"],
        email: row["Email"]
      )

      org = Organization.find_by(
        client_account_id: current_user.client_account_id,
        organization_code: row["Organization"]
      )

      unless org
        org = Organization.create(
          user_id: current_user.id,
          client_account_id: current_user.client_account_id,
          organization_code: row["Organization"],
          organization_name: row["Organization Name"],
          unloco: row["Working Location"]
        )
      end

      contact.organization_id = org.id if org

      contact.assign_attributes(
        contact_name: row["Contact Name"],
        organization_code: row["Organization"],
        organization_name: row["Organization Name"],
        working_location: row["Working Location"],
        title: row["Title"],
        email: row["Email"],
        job_category: row["Job Category"],
        password_instruction_sent_by: row["Password Instruction Sent By"],
        password_instruction_last_sent_time: row["Password Instruction Last Sent Time"],
        active: Utils.to_boolean(row["Active"]),
        primary_workplace: row["Primary Workplace"],
        web_access: Utils.to_boolean(row["Web Access"]),
        verified: Utils.to_boolean(row["Verified"]),
        created_by: row["Created By"],
        created_time_utc: row["Created Time (UTC)"],
        last_edit: row["Last Edit"],
        last_edited_time_utc: row["Last Edited Time (UTC)"],
        csv: Utils.to_boolean(row["CSV"]),
        phone: row["Phone"],
        mobile: row["Mobile"],
        notify_mode: row["Notify Mode"],
        branch_address: row["Branch Address"],
        web_access_superseded: Utils.to_boolean(row["Web Access Superseded"]),
        organization_id: org.id
      )

      contact.save if contact.valid? && contact.changed?

      redirect_to organizations_path, notice: "Contacts uploaded successfully"
    end
  end

  def show
  end
end

app/views/organizations/import.html.erb
<h1>Import Organizations</h1>
<p>Import organizations from an Excel or CSV file export from Cargowise</p>
<% if current_user.client_account.present? %>
  <%= form_tag organizations_upload_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
<% else %>
  <p>You need to have a client account to import organizations</p>
  <%= link_to "Add a client account", new_client_account_path %>
<% end %>

app/views/organizations/import_contacts.html.erb
<h1>Import Organization Contacts</h1>
<p>Import contacts from an Excel or CSV file export from Cargowise</p>
<% if current_user.client_account.present? %>
  <%= form_tag organizations_upload_contacts_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
<% else %>
  <p>You need to have a client account to import organizations</p>
  <%= link_to "Add a client account", new_client_account_path %>
<% end %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Organizations</h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= @organization_ids.size %> saved organizations</h6>
        <p class="card-text">Import your organizations from Cargowise</p>
        <%= link_to "Import Organizations", organizations_import_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Contacts</h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= @organization_contacts_size %> saved contacts</h6>
        <p class="card-text">Import contacts for your organizations from Cargowise</p>
        <%= link_to "Import Organization Contacts", organizations_import_contacts_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>