config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'api/eadaptor' => 'api#eadaptor'
  post 'api/eadaptor' => 'api#eadaptor'
  put 'api/eadaptor' => 'api#eadaptor'

  resources :organizations, except: [:show]
  resources :client_accounts
  resources :email
  resources :shipments
  resources :invoices do
    collection do
      get :export
    end
  end

  get 'email_sync' => 'email#sync'

  get 'organizations/import' => 'organizations#import'
  get 'organizations/import_contacts' => 'organizations#import_contacts'
  post 'organizations/upload' => 'organizations#upload'
  post 'organizations/upload_contacts' => 'organizations#upload_contacts'

  post "google/auth", to: "google#auth"
  get "google/auth", to: "google#auth"

  post "oauth2callback", to: "google#auth"
  get "oauth2callback", to: "google#auth"

  post 'cargowise_shipment' => 'cargowise#create_shipment'

  root to: 'static#index'
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  has_and_belongs_to_many :emails
  belongs_to :client_account
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shipment, only: %i[show edit update destroy]

  def create
    @shipment = Shipment.new(shipment_params)
    @shipment.client_account = current_user.client_account
    @email = load_user_email(params[:email_id]) if params[:email_id]
    @shipment.emails << @email if @email
    @shipment.save
    redirect_to shipment_path(@shipment)
  end

  def destroy
  end

  def edit
  end

  def index
    @shipments = account_shipments
  end

  def new
    if params[:email_id]
      @email = load_user_email(params[:email_id])
    end

    @shipment = Shipment.new(client_account: current_user.client_account)

    if @email
      @shipment.emails << @email
      email = @email
      @documents = email.documents.where.not(content: nil).where.not(irrelevant: true)
    end

    to = "to: #{email.to}"
    from = "from: #{email.from}"
    subject = "subject: #{email.subject}"
    body = "body: #{email.body}"
    email_string = [to, from, subject, body, email.date].join("\n")
    shipment_data = OpenAiService.new.extract_shipment(email_string)
    @documents.each do |doc|
      begin
        shipment_data.merge!(OpenAiService.new.extract_shipment(doc.content))
      rescue
        next
      end
    end

    shipment_data = clean_and_format_shipment_data(shipment_data)

    @shipment.assign_attributes(shipment_data)
  end

  def show
  end

  def update
  end

  private
  def clean_and_format_shipment_data(data)
    data["origin_location"] = origin_location_from_data(data)
    data["destination_location"] = destination_location_from_data(data)
    # sanitize to shipment params
    data = data.select { |k, v| Shipment.column_names.include?(k) }
  end

  def origin_location_from_data(data)
    return unless data.present? && data.is_a?(Hash)
    data = data.select { |k, v| k.match?(/origin/i) && v.present?}
    data.transform_keys! { |k| k.gsub('origin_', '') }
    data["state"] = data.delete("state_code")
    data["country"] = data.delete("country_code")

    location = Location.find_by(code: data['code'])
    location ||= Location.find_by(iata: data['iata'])

    return location.code if location
    location = Organization.find_by(data)
    location ||= Organization.find_by(data.except("name"))

    location.unloco
  end

  def destination_location_from_data(data)
    return unless data.present? && data.is_a?(Hash)
    data = data.select { |k, v| k.match?(/destination/i) && v.present?}
    data.transform_keys! { |k| k.gsub('destination_', '') }
    data["state"] = data.delete("state_code")
    data["country"] = data.delete("country_code")

    location = Location.find_by(code: data['code'])
    location ||= Location.find_by(iata: data['iata'])

    return location.code if location
    location = Organization.find_by(data)
    location ||= Organization.find_by(data.except("name"))

    location.unloco
  end

  def set_shipment
    @shipment = account_shipments.find_by(id: params[:id])
  end

  def account_shipments
    Shipment.where(client_account_id: current_user.client_account_id)
  end

  def load_user_email(id)
    email = Email.find_by(id: id)
    return unless email.owned_by?(current_user)
    email
  end

  def shipment_params
    params.require(:shipment).permit(
      :platform_shipment_id,
      :platform_consol_id,
      :origin_code,
      :destination_code,
      :transport_type,
      :container_type,
      :shipment_type,
      :shipper_code,
      :consignee_code,
      :customer_code,
      :weight,
      :weight_units,
      :volume,
      :volume_units,
      :length,
      :width,
      :height,
      :measurement_units,
      :po_number,
      :bol_number,
      :shipped_date,
      :issue_date,
      :eta,
      :etd,
      :description,
      :commodity_code,
      :initial_platform,
      :destination_platform,
      :line_items
    )
  end
end

app/views/shipments/_form.html.erb
<%= form_with(model: @shipment, local: true) do |form| %>
  <%= hidden_field_tag :email_id, params[:email_id] %>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :platform_shipment_id %>
        <%= form.text_field :platform_shipment_id, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :platform_consol_id %>
        <%= form.text_field :platform_consol_id, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :origin_code %>
        <%= form.text_field :origin_code, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :destination_code %>
        <%= form.text_field :destination_code, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :transport_type %>
        <%= form.text_field :transport_type, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :container_type %>
        <%= form.text_field :container_type, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :shipment_type %>
        <%= form.text_field :shipment_type, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :shipper_code %>
        <%= form.text_field :shipper_code, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :consignee_code %>
        <%= form.text_field :consignee_code, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :customer_code %>
        <%= form.text_field :customer_code, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :weight %>
        <%= form.text_field :weight, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :weight_units %>
        <%= form.text_field :weight_units, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :volume %>
        <%= form.text_field :volume, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :volume_units %>
        <%= form.text_field :volume_units, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :length %>
        <%= form.text_field :length, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :width %>
        <%= form.text_field :width, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :height %>
        <%= form.text_field :height, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :measurement_units %>
        <%= form.text_field :measurement_units, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :po_number %>
        <%= form.text_field :po_number, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :bol_number %>
        <%= form.text_field :bol_number, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :shipped_date %>
        <%= form.date_field :shipped_date, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :issue_date %>
        <%= form.date_field :issue_date, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :eta %>
        <%= form.datetime_local_field :eta, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :etd %>
        <%= form.datetime_local_field :etd, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :commodity_code %>
        <%= form.text_field :commodity_code, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :initial_platform %>
        <%= form.text_field :initial_platform, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :destination_platform %>
        <%= form.text_field :destination_platform, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <div class="mb-3">
        <%= form.label :line_items %>
        <%= form.text_field :line_items, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="mb-3">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/shipments/create.html.erb
<%= render 'form', shipment: @shipment %>

app/views/shipments/edit.html.erb
<%= render 'form', shipment: @shipment %>

app/views/shipments/index.html.erb
<h1>Shipments</h1>
<table class="table">
  <thead>
    <tr>
      <th>Platform Shipment ID</th>
      <th>BOL #</th>
      <th>PO #</th>
      <th>Origin Code</th>
      <th>Destination</th>
      <th>Customer</th>
      <th>Shipper</th>
      <th>Consignee</th>
      <th>Shipment Date</th>
      <th>ETD</th>
      <th>ETA</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.platform_shipment_id %></td>
        <td><%= shipment.bol_number %></td>
        <td><%= shipment.po_number %></td>
        <td><%= shipment.origin_code %></td>
        <td><%= shipment.destination_code %></td>
        <td><%= shipment.customer_code %></td>
        <td><%= shipment.shipper_code %></td>
        <td><%= shipment.consignee_code %></td>
        <td><%= shipment.shipped_date %></td>
        <td><%= shipment.etd %></td>
        <td><%= shipment.eta %></td>
        <td>
          <%= link_to "Show", shipment_path(shipment), class: "btn btn-primary" %>
          <%= link_to "Edit", edit_shipment_path(shipment), class: "btn btn-secondary" %>
          <%= link_to "Delete", shipment_path(shipment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shipments/new.html.erb
<%= render 'form', shipment: @shipment %>

app/views/shipments/show.html.erb
<%# show all fields for @shipment as readonly %>
<h1>Shipment</h1>
<h3>BOL #: <%= @shipment.bol_number.present? ? @shipment.bol_number : "N/A"  %></h3>
<h3>PO #: <%= @shipment.po_number.present? ? @shipment.po_number : "N/A" %></h2>
<h3>Platform Shipment ID: <%= @shipment.platform_shipment_id.present? ? @shipment.platform_shipment_id : "N/A" %></h3>

<%# Edit, Push to Cargowise %>
<div class="row m-3">
  <div class="col-md-6">
    <%= link_to "Edit", edit_shipment_path(@shipment), class: "btn btn-secondary" %>
    <%= link_to "Push to Cargowise", cargowise_shipment_path(shipment_id: @shipment.id), class: "btn btn-primary", data: { turbo_method: :post } %>
  </div>
</div>

<table class="table-bordered">
  <% @shipment.attributes.except("id", "created_at", "updated_at", "platform_shipment_id", "bol_number", "po_number").each do |key, value| %>
    <tr>
      <td><strong><%= key.humanize.upcase %></strong></td>
      <td><%= value %></td>
    </tr>
  <% end %>
</table>