config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'api/eadaptor' => 'api#eadaptor'
  post 'api/eadaptor' => 'api#eadaptor'
  put 'api/eadaptor' => 'api#eadaptor'

  resources :organizations, except: [:show]
  resources :client_accounts
  resources :email
  resources :shipments
  resources :invoices do
    collection do
      get :export
    end
  end

  get 'email_sync' => 'email#sync'

  get 'organizations/import' => 'organizations#import'
  get 'organizations/import_contacts' => 'organizations#import_contacts'
  post 'organizations/upload' => 'organizations#upload'
  post 'organizations/upload_contacts' => 'organizations#upload_contacts'

  post "google/auth", to: "google#auth"
  get "google/auth", to: "google#auth"

  post "oauth2callback", to: "google#auth"
  get "oauth2callback", to: "google#auth"

  post 'cargowise_shipment' => 'cargowise#create_shipment'

  root to: 'static#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-mdb-theme="dark">
  <head>
    <title>Enaibl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#b38bf5">
    <meta name="msapplication-TileColor" content="#c4fc6f">
    <meta name="theme-color" content="#c4fc6f">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- MDBootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/mdb-ui-kit@3.11.0/dist/css/mdb.min.css" rel="stylesheet">

    <!-- FontAwesome (Optional, for icons) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Your custom Rails styles -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
      const isSystemThemeSetToDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

      if (isSystemThemeSetToDark) {
        document.documentElement.dataset.mdbTheme = "dark";
      } else {
        document.documentElement.dataset.mdbTheme = "light";
      }

    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand mx-2" href="<%= root_path %>">Enaibl
          <%= image_tag 'enaibl_prototype.png', alt: 'Enaibl', width: 51, height: 38, class: "mx-2" %>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mb-2 mb-lg-0">
            <% if current_user %>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle d-flex align-items-center"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false"
                  data-turbo-action="replace"
                >
                  <div class="avatar-circle d-flex justify-content-center align-items-center">
                    <% if current_user && current_user.first_name && current_user.last_name %>
                      <%= current_user.first_name[0].upcase + current_user.last_name[0].upcase %>
                    <% else %>
                      <%= current_user.email[0].upcase %>
                    <% end %>
                  </div>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><%= link_to "My profile", edit_user_registration_path, class: "dropdown-item" %></li>
                  <%= link_to "Organization Account", client_accounts_path, class: "dropdown-item" %>
                  <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "dropdown-item" %>
                </ul>
              </li>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: "nav-item btn btn-primary px-3 mx-2", role: "button", data: "mdb-ripple-init" %>
              <li class="nav-item"><a class="nav-link" href="/users/sign_in">Log in</a></li>
            <% end %>
            <% if current_user %>
              <li><%= link_to "Emails", email_index_path, class: "nav-link" %></li>
              <li><%= link_to "Invoices", invoices_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Shipments", shipments_path, class: "nav-link" %></li>
              <li><%= link_to "Organizations", organizations_path, class: "nav-link" %></li>
            <% end %>
            <li class="nav-item align-items-center d-flex mx-3 mb-2" >
              <i class="fas fa-sun"></i>
              <!-- Default switch -->
              <div class="ms-2 form-check form-switch">
                <input class="form-check-input" type="checkbox" role="switch" id="themingSwitcher" />
              </div>
              <i class="fas fa-moon"></i>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- MDBootstrap JS -->
    <script src="/mdb/js/mdb.umd.min.js"></script>
    <script>
      const themeStitcher = document.getElementById("themingSwitcher");

      // if undefined, set theme based on system theme
      if (isSystemThemeSetToDark === undefined) {
        const isSystemThemeSetToDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      }

      // set toggler position based on system theme
      if (isSystemThemeSetToDark) {
        themeStitcher.checked = true;
      }

      // add listener to theme toggler
      themeStitcher.addEventListener("change", (e) => {
        toggleTheme(e.target.checked);
      });

      const toggleTheme = (isChecked) => {
        const theme = isChecked ? "dark" : "light";

        document.documentElement.dataset.mdbTheme = theme;
      }

      function mdbConfig() {
        document.querySelectorAll("[data-mdb-toggle='dropdown']").forEach((dropdown) => {
          document.querySelectorAll("[data-mdb-toggle='dropdown']").forEach((dropdown) => {
            new mdb.Dropdown(dropdown);
          });

          document.querySelectorAll("[data-mdb-toggle='collapse']").forEach((collapse) => {
            new mdb.Collapse(collapse);
          });

          document.querySelectorAll("[data-mdb-ripple-color]").forEach((ripple) => {
            new mdb.Ripple(ripple);
          });
        });
      }

      document.addEventListener("turbo:load", function() {
        mdbConfig();
      });
    </script>

  </body>
</html>